config/routes.rb
Rails.application.routes.draw do
  resources :suppilers
  resources :own_orders
  resources :own_design_products
  get 'cart/show'
  devise_for :deliverymen
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :order_products
  resources :orders
  resources :products
  resources :categories


  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    
  }
  resources :users
  get "edit_password/:user_id" => "users#edit_password", as: :edit_password
  patch "update_password/:user_id" => "users#update_password"
  get "edit_profile_info/:user_id" => "users#edit_profile_info", as: :edit_profile_info
  patch "update_profile_info/:user_id" => "users#update_profile_info"
  get "edit_profile_password/:user_id" => "users#edit_profile_password", as: :edit_profile_password
  patch "update_profile_password/:user_id" => "users#update_profile_password"
  get "user_profile/:user_id" => "users#user_profile", as: :user_profile

  get "cart" => 'cart#show'
  get "cart/add/:id" => "cart#add", :as => :add_to_cart
  post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
  post "cart/checkout" => "cart#checkout", :as => :checkout
  get "cart/checkout_page" => "cart#checkout_page", as: :checkout_page


  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products


    def to_s
        self.name
    end
end

app/models/deliveryman.rb
class Deliveryman < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
    has_many :products
    belongs_to :user

    scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
    scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}
  
    COMPLETE = "complete"
    IN_PROGRESS = "in_progress"

    
  
   
    def checkout!
      if order_products.present?
      self.order_date = Time.now
      self.save
      else 
        self.save!
      end
    end

    # def recalculate_price!
    #   self.total_price = order_products.inject(0.0){|sum, line_item| sum += line_item.price }
    #   save!
    # end
  
    def recalculate_price!
      self.amount = order_products.inject(0.0){|sum, order_product| sum += order_product.price}
      save!
    end

    def state
      order_date.nil? ? IN_PROGRESS : COMPLETE
    end
  
    
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order, dependent: :destroy
    belongs_to :product

    def to_s
        self.product.name
    end

end

app/models/own_design_product.rb
class OwnDesignProduct < ApplicationRecord
  belongs_to :user
  has_many :own_orders,  dependent: :destroy
  has_many_attached :images
end

app/models/own_order.rb
class OwnOrder < ApplicationRecord
  belongs_to :own_design_product
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image 
    # accepts_nested_attributes_for :images, :allow_destroy => true  
    belongs_to :category
    has_many :order_products

    def to_s
        self.name
    end

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :suppiler

  def to_s
    self.purchaseproduct
  end
end

app/models/purchase_detail.rb
class PurchaseDetail < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
  belongs_to :raw
end

app/models/raw.rb
class Raw < ApplicationRecord

    def to_s
        self.raw_name
    end
end

app/models/suppiler.rb
class Suppiler < ApplicationRecord

    def to_s
        self.suppiler_name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders, dependent: :destroy
      has_many :own_design_products

         def to_s
          self.name
         end
end

app/controllers/own_orders_controller.rb
class OwnOrdersController < InheritedResources::Base

  private

    def own_order_params
      params.require(:own_order).permit(:own_design_product_id, :status, :own_design_product_date)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/own_orders_helper.rb
module OwnOrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppilers_helper.rb
module SuppilersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/own_orders/_form.html.erb
<%= form_with(model: own_order, local: true) do |form| %>
  <% if own_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(own_order.errors.count, "error") %> prohibited this own_order from being saved:</h2>

      <ul>
      <% own_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :own_design_product_id %>
    <%= form.text_field :own_design_product_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :own_design_product_date %>
    <%= form.datetime_select :own_design_product_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/own_orders/edit.html.erb
<h1>Editing Own Order</h1>

<%= render 'form', own_order: @own_order %>

<%= link_to 'Show', @own_order %> |
<%= link_to 'Back', own_orders_path %>

app/views/own_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Own Orders</h1>

<table>
  <thead>
    <tr>
      <th>Own design product</th>
      <th>Status</th>
      <th>Own design product date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @own_orders.each do |own_order| %>
      <tr>
        <td><%= own_order.own_design_product %></td>
        <td><%= own_order.status %></td>
        <td><%= own_order.own_design_product_date %></td>
        <td><%= link_to 'Show', own_order %></td>
        <td><%= link_to 'Edit', edit_own_order_path(own_order) %></td>
        <td><%= link_to 'Destroy', own_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Own Order', new_own_order_path %>

app/views/own_orders/new.html.erb
<h1>New Own Order</h1>

<%= render 'form', own_order: @own_order %>

<%= link_to 'Back', own_orders_path %>

app/views/own_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Own design product:</strong>
  <%= @own_order.own_design_product %>
</p>

<p>
  <strong>Status:</strong>
  <%= @own_order.status %>
</p>

<p>
  <strong>Own design product date:</strong>
  <%= @own_order.own_design_product_date %>
</p>

<%= link_to 'Edit', edit_own_order_path(@own_order) %> |
<%= link_to 'Back', own_orders_path %>