config/routes.rb
Rails.application.routes.draw do
  resources :suppilers
  resources :own_orders
  resources :own_design_products
  get 'cart/show'
  devise_for :deliverymen
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :order_products
  resources :orders
  resources :products
  resources :categories


  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    
  }
  resources :users
  get "edit_password/:user_id" => "users#edit_password", as: :edit_password
  patch "update_password/:user_id" => "users#update_password"
  get "edit_profile_info/:user_id" => "users#edit_profile_info", as: :edit_profile_info
  patch "update_profile_info/:user_id" => "users#update_profile_info"
  get "edit_profile_password/:user_id" => "users#edit_profile_password", as: :edit_profile_password
  patch "update_profile_password/:user_id" => "users#update_profile_password"
  get "user_profile/:user_id" => "users#user_profile", as: :user_profile

  get "cart" => 'cart#show'
  get "cart/add/:id" => "cart#add", :as => :add_to_cart
  post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
  post "cart/checkout" => "cart#checkout", :as => :checkout
  get "cart/checkout_page" => "cart#checkout_page", as: :checkout_page


  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products


    def to_s
        self.name
    end
end

app/models/deliveryman.rb
class Deliveryman < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
    has_many :products
    belongs_to :user

    scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
    scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}
  
    COMPLETE = "complete"
    IN_PROGRESS = "in_progress"

    
  
   
    def checkout!
      if order_products.present?
      self.order_date = Time.now
      self.save
      else 
        self.save!
      end
    end

    # def recalculate_price!
    #   self.total_price = order_products.inject(0.0){|sum, line_item| sum += line_item.price }
    #   save!
    # end
  
    def recalculate_price!
      self.amount = order_products.inject(0.0){|sum, order_product| sum += order_product.price}
      save!
    end

    def state
      order_date.nil? ? IN_PROGRESS : COMPLETE
    end
  
    
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order, dependent: :destroy
    belongs_to :product

    def to_s
        self.product.name
    end

end

app/models/own_design_product.rb
class OwnDesignProduct < ApplicationRecord
  belongs_to :user
  has_many :own_orders,  dependent: :destroy
  has_many_attached :images
end

app/models/own_order.rb
class OwnOrder < ApplicationRecord
  belongs_to :own_design_product
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image 
    # accepts_nested_attributes_for :images, :allow_destroy => true  
    belongs_to :category
    has_many :order_products

    def to_s
        self.name
    end

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :suppiler

  def to_s
    self.purchaseproduct
  end
end

app/models/purchase_detail.rb
class PurchaseDetail < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
  belongs_to :raw
end

app/models/raw.rb
class Raw < ApplicationRecord

    def to_s
        self.raw_name
    end
end

app/models/suppiler.rb
class Suppiler < ApplicationRecord

    def to_s
        self.suppiler_name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders, dependent: :destroy
      has_many :own_design_products

         def to_s
          self.name
         end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :color, :size, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/own_orders_helper.rb
module OwnOrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppilers_helper.rb
module SuppilersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container-fluid mr-3">
    <div class="row ">
        <% @products.each do |product| %> 
          
            <div class="col-md-3">
                <%= link_to product_path(product), :action => 'go', class:"no-underline" do %>
                  <div class="card align-items-center">
                  <div class="view overlay">
                  <div class=" text-center pt-2"><%= image_tag (product.image), class: "product card-img-top"%></div>
                    <div class="mask rgba-white-slight"></div>
                  </div>
                  <div class="card-body text-center">                  
                    <h5 class="grey-text"><%= product.category%></h5>  
                  <h5>
                    <strong>
                    <i class="fas fa-circle" style="color: <%= product.color %>"></i>
                      <span class="dark-grey-text"><%= product.name%>
                     
                      </span>
                    </strong>
                  </h5>
                  <h4 class="font-weight-bold blue-text">
                    <strong>$ <%= product.price%></strong>
                  </h4>
                </div>
                  </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-6 mt-5">
          <%= image_tag @product.image, class: "product", size: 40*10 %>
      </div>
      <div class="col-md-5 mt-5 float-right">
       <strong> Product Name: </strong> <%= @product.name %>
        <br><br>
    <strong>Price:</strong> <%= number_to_currency  @product.price %>  
      
        (<%= link_to "Add to Card", add_to_cart_path(@product.id) %>)<br><br>
      <strong> Category Name: </strong> <%= @product.category %><br><br>
      
      <strong> Available Color : </strong><span><i class="fas fa-circle" style="color: <%=@product.color%>"></i></span>
      </div>
  </div>
</div>



  

  
  <h5>
    <strong>
      
    </p>

</div>

<div style="clear:both;"></div>

</div>
<!--Card content-->

</div>