config/routes.rb
Rails.application.routes.draw do
  resources :suppilers
  resources :own_orders
  resources :own_design_products
  get 'cart/show'
  devise_for :deliverymen
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :order_products
  resources :orders
  resources :products
  resources :categories


  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
    
  }
  resources :users
  get "edit_password/:user_id" => "users#edit_password", as: :edit_password
  patch "update_password/:user_id" => "users#update_password"
  get "edit_profile_info/:user_id" => "users#edit_profile_info", as: :edit_profile_info
  patch "update_profile_info/:user_id" => "users#update_profile_info"
  get "edit_profile_password/:user_id" => "users#edit_profile_password", as: :edit_profile_password
  patch "update_profile_password/:user_id" => "users#update_profile_password"
  get "user_profile/:user_id" => "users#user_profile", as: :user_profile

  get "cart" => 'cart#show'
  get "cart/add/:id" => "cart#add", :as => :add_to_cart
  post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
  post "cart/checkout" => "cart#checkout", :as => :checkout
  get "cart/checkout_page" => "cart#checkout_page", as: :checkout_page


  root to: 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products


    def to_s
        self.name
    end
end

app/models/deliveryman.rb
class Deliveryman < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
    has_many :products
    belongs_to :user

    scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
    scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}
  
    COMPLETE = "complete"
    IN_PROGRESS = "in_progress"

    
  
   
    def checkout!
      if order_products.present?
      self.order_date = Time.now
      self.save
      else 
        self.save!
      end
    end

    # def recalculate_price!
    #   self.total_price = order_products.inject(0.0){|sum, line_item| sum += line_item.price }
    #   save!
    # end
  
    def recalculate_price!
      self.amount = order_products.inject(0.0){|sum, order_product| sum += order_product.price}
      save!
    end

    def state
      order_date.nil? ? IN_PROGRESS : COMPLETE
    end
  
    
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order, dependent: :destroy
    belongs_to :product

    def to_s
        self.product.name
    end

end

app/models/own_order.rb
class OwnOrder < ApplicationRecord
  belongs_to :own_design_product
  
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image 
    # accepts_nested_attributes_for :images, :allow_destroy => true  
    belongs_to :category
    has_many :order_products

    def to_s
        self.name
    end

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :suppiler

  def to_s
    self.purchaseproduct
  end
end

app/models/purchase_detail.rb
class PurchaseDetail < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
  belongs_to :raw
end

app/models/raw.rb
class Raw < ApplicationRecord

    def to_s
        self.raw_name
    end
end

app/models/suppiler.rb
class Suppiler < ApplicationRecord

    def to_s
        self.suppiler_name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders, dependent: :destroy
      has_many :own_design_products

         def to_s
          self.name
         end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/own_orders_helper.rb
module OwnOrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppilers_helper.rb
module SuppilersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BigFurniture</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>




  <% if user_signed_in? %>
  <nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
  <a class="navbar-brand" href="#">BIG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to "Product", products_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Order List", orders_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Order Design", new_own_design_product_path, class: "nav-link" %>
      </li>

      

      <li class="nav-item">
      <%= link_to "Own Design Order List", own_design_products_path, class: "nav-link" %>
   
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
    
      <li class="nav-item">
       <%= link_to  "", cart_path, class: "fas fa-shopping-cart nav-link waves-effect waves-light", style: "text-decoration:none;" %>
      </li>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <%= link_to  "View Profiles", user_profile_path(current_user), class: "dropdown-item" %>
          <%= link_to  "Change Password", edit_profile_password_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
           <%= link_to("<span class='glyphicon glyphicon-log-out'></span> Log Out".html_safe,
              destroy_user_session_path, 
              :method => :delete,
              :data => { :confirm => "Are you sure to Log Out?" }, class: "dropdown-item") %>               </div>
      </li>
    </ul>
  </div>
</nav>
 <%=yield%> 
    
  <%else%>

 

   <%=yield%>
  

  <%end%>  
  </body>
</html>